# Generated by Django 3.2.25 on 2025-11-12 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_file', models.FileField(upload_to='models/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('feature_columns', models.TextField(blank=True, null=True)),
                
                # FIXED: JSONField removed (not supported in SQLite)
                # ('meta', models.JSONField(blank=True, null=True)),
                ('meta', models.TextField(blank=True, null=True)),  # <--- SAFE WITH SQLITE
            ],
        ),
        migrations.CreateModel(
            name='UploadedDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='datasets/')),
                ('original_name', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.AddField(
            model_name='trainedmodel',
            name='uploaded_dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.uploadeddataset'),
        ),
    ]
