# Generated by Django 3.2.25 on 2025-11-23 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_auto_20251112_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainedmodel',
            name='feature_columns',
            field=models.TextField(blank=True, help_text='JSON-encoded list of feature column names', null=True),
        ),
        migrations.AlterField(
            model_name='trainedmodel',
            name='meta',
            field=models.TextField(blank=True, help_text='JSON-encoded metadata (e.g., cat_cols, label_col)', null=True),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('experience_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('current_company', models.CharField(blank=True, max_length=120)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('predicted_role', models.CharField(blank=True, max_length=120)),
                ('predicted_confidence', models.FloatField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
