# Generated by Django 3.2.25 on 2025-11-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_predictionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionhistory',
            name='metadata',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='predictionhistory',
            name='skills',
            field=models.TextField(blank=True),
        ),
    ]
